name: CI

on: [release]

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Tesssst
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          # Install Sentry CLI
          curl -sL https://sentry.io/get-cli/ | bash
